# Generated by Django 4.1.2 on 2022-10-26 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='status')),
            ],
            options={
                'verbose_name_plural': 'Client Status',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('mobile', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Portable')),
                ('first_name', models.CharField(max_length=25, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nom')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('company_name', models.CharField(max_length=100, verbose_name='Société')),
                ('sales_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('status', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='clients.clientstatus', verbose_name='Status du Client')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
