# Generated by Django 4.1.2 on 2022-10-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='status')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='clients.clientstatus', verbose_name='client_status'),
        ),
    ]
