# Generated by Django 4.1.2 on 2022-10-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_company_name_alter_client_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatus',
            options={'verbose_name_plural': 'Client Status'},
        ),
    ]
