# Generated by Django 4.1.2 on 2022-10-26 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('status', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Events Status',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('event_date', models.DateField(blank=True, verbose_name="Date de l'évenement")),
                ('attendees', models.PositiveIntegerField(default=0, verbose_name='Nb de personnes')),
                ('notes', models.TextField(blank=True, verbose_name='Infos')),
                ('contract_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='contracts.contract', verbose_name='Contract')),
                ('event_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventstatus', verbose_name='Etat')),
                ('support_contact_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Chargé de l'événement")),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
