# Generated by Django 4.1.2 on 2022-10-16 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_alter_client_company_name_alter_client_date_created_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=0, verbose_name='Nb de personnes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crée le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, verbose_name="Date de l'évenement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventstatus', verbose_name="Etat de l'évenement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(verbose_name='Infos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="Chargé de l'événement"),
        ),
    ]
