# Generated by Django 4.1.2 on 2022-10-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_attendees_alter_event_client_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name_plural': 'Events Status'},
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Status'),
        ),
    ]
