# Generated by Django 4.1.2 on 2022-10-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_contract_sales_contact_id_and_more'),
        ('events', '0003_alter_eventstatus_options_alter_eventstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client_id',
        ),
        migrations.AddField(
            model_name='event',
            name='contract_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='contracts.contract', verbose_name='Contract'),
            preserve_default=False,
        ),
    ]
