# Generated by Django 4.1.2 on 2022-10-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
