# Generated by Django 4.1.2 on 2022-10-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employee_date_joined_employee_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
