# Generated by Django 4.1.2 on 2022-10-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_groups_employee_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.group'),
        ),
    ]
