# Generated by Django 4.1.2 on 2022-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_employee_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='group'),
        ),
    ]
