# Generated by Django 4.1.2 on 2022-10-16 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Crée le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.group', verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Portable'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Téléphoneé'),
        ),
    ]
