# Generated by Django 4.1.2 on 2022-10-16 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_employee_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Salariée'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Groupe', 'verbose_name_plural': 'Groupes'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Service'),
        ),
    ]
