# Generated by Django 4.1.2 on 2022-10-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0007_alter_employee_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorization', to='auth.permission', verbose_name='autorisation'),
        ),
    ]
