# Generated by Django 4.1.2 on 2022-10-17 07:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0008_group_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.AddField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(null=True, related_name='authorization', to='auth.permission', verbose_name='autorisation'),
        ),
    ]
