# Generated by Django 4.1.2 on 2022-10-13 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_clientstatus_alter_client_sales_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('payment_due', models.DateField(blank=True)),
                ('amount_float', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='client_id')),
                ('sales_contact_id', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='sale_contact_id')),
            ],
        ),
    ]
