# Generated by Django 4.1.2 on 2022-10-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('payment_due', models.DateField(blank=True, verbose_name='Date de réglement')),
                ('amount_float', models.FloatField(default=0, verbose_name='Montant')),
                ('status', models.BooleanField(default=False, verbose_name='Validé')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'événement")),
                ('client_id', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
