# Generated by Django 4.1.2 on 2022-10-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clientstatus_options'),
        ('contracts', '0002_alter_contract_amount_float_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact_id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client_id',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
    ]
