# Generated by Django 4.1.2 on 2022-10-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('pk',)},
        ),
    ]
